### PR TITLE
add 782

### PR DESCRIPTION
**Pull request by reelsense**
I ripped this summary from https://www.noagendaplayer.com/listen/782, so if these summaries are insufficient don't feel bad about rejecting this pull request. It only took like 3 min. I just wanted to help

### CODE REVIEW

**Comment by K8TIY** [comment]
Thanks and TYFYC, I will contact you about your work which I appreciate. 4 wks vacation plus a broken leg has me twiddling my thumbs here in Gitmo Mitten. -- Cheers DE Fudgefountain K8TIY

**Comment by K8TIY** [comment]
A slightly longer explanation: while on vacation away from my primary workstation I do pen-and-paper summaries and then enter them manually. I had already written the summary for Show 782 when you submitted the request, so that is why I am rejecting -- I just now entered and uploaded my existing 782 summary, and will be playing catch-up with the large stack of paper for the intervening shows for a while yet :-/ TYFYC again. This is the first time anyone has tried to contribute, so I was really surprised and pleased.

Cheers from Sir Fudgefountain

**Comment by reelsense** [comment]
ITM. I read your readme and hoped you wrote them. I have seen many of these transcription projects die over the years and I notices yours dropped in activity. I hoped you didn't fall behind and give up, so I wanted to submit something to see what would happen. Thanks for clearing that up.

I've been mirroring your repository on the NA github group: https://github.com/No-Agenda . I'll resend your invite if you want to join. 

Remember, wash your hands after touching any raw meat. :P

**Comment by K8TIY** [comment]
I'll _try_ not to let the project lapse! I often find the summaries quite useful for myself if I want to go back and find something interesting or funny.

I just joined the group -- invite was still valid! Cool, thanks.

As you can see, I'm trying to burn thru the backlog. Just starting to go to town on 785.

Here's something you can do if you stumble on the info: occasionally I miss out on the timestamp for the beginning-of-show clip (784 for example). If you happen to be an occasional old-show-listener and you find a "lost timestamp", please send it on. It annoys me when I miss them but am generally not up for a third listen, just to spot the BoS quote thats (usually) not critical content.

**Pull request closed without merging**
